defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "vibcreg-imagenet100-linear"
pretrained_feature_extractor: "/itet-stor/zdavid/net_scratch/Self-Supervised-Learning-with-Predictability-Minimization/trained_models/vibcreg/9tjxisb5/vibcreg-imagenet100-9tjxisb5-ep=399.ckpt"
backbone:
  name: "resnet18"
pretrain_method: "vibcreg"
data:
  dataset: imagenet100
  train_path: "/itet-stor/zdavid/net_scratch/data/ILSVRC2012_img_train_100"
  val_path: "/itet-stor/zdavid/net_scratch/data/ILSVRC2012_img_val_100"
  format: "dali"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.3
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
