defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "cl_lin_pred_min-imagenet100"
method: "cl_lin_pred_min"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 128
  mask_fraction: 0.5
  lamb: 0.2
  ridge_lambd: 0
  proj_size: 3
data:
  dataset: imagenet100
  train_path: "/itet-stor/maotth/net_scratch/data/ILSVRC2012_img_train_100"
  val_path: "/itet-stor/maotth/net_scratch/data/ILSVRC2012_img_val_100"
  format: "dali"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: False
# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
